### ISSUE TITLE
I have issues...

### ISSUE THREAD

**Issue by DRL** [rjchallis/assembly_stats#1]
Hi Rich, 

made the plots for two assemblies with the previous version and they are great.

what do you think about replacing the colouring of the outer GC-band with a wiggle/dot-plot of GC and N's for each scaffold (using fixed windowsize or scaffold/contig mean)? 

that way one could tell wether for example half of the biggest scaffold is made up of N's ... or if you have GC outlier in the biggest scaffolds.

cheers, 

dom

**Comment by rjchallis** [comment]
Sounds like a good way to increase the data-density of the plot - I like it!

Should be straightforward to implement so expect to see it in an update soon...

**Comment by rjchallis** [comment]
Finally released a version with this implemented
